drop table if exists member CASCADE;

create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

insert into member(name) values('spring');

delete from member;

update MEMBER as m
set m.NAME = '균지니'
where m.ID = 16;
